### ISSUE TITLE
react-async peer-dependency issue while installing

### ISSUE THREAD

**Issue by apaatsio** [chadpaulson/react-isomorphic-video-game-search#4]
I was able to install the global packages but when running `npm install` I'm getting the following error:

```
[antti@a1 react-isomorphic-video-game-search]$ npm install
npm ERR! Linux 3.18.11-1-MANJARO
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-async does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router-component@0.23.3 wants react-async@~2.0.0
```

I also tried to install older react-tools (react-tools@0.12) and I tried on both nodejs 0.10.35 and nodejs 0.12.2

**Comment by chadpaulson** [comment]
Thanks for taking the time to review and contribute (#5) to the project.  This project is a snapshot of @WarpPipe's R&D progress from several months ago and I have done a poor job keeping it current due to competing interests, thereby making contributions awkward and difficult.

While I do have plans to update this demo, I do not plan on moving forward with react-async and react-router-component and would like to keep this collection of dependencies under React 0.12.x for the time being.  I just pushed a temporary solution which should solve the peer dependency issue.

Be on the lookout for a new branch which will likely be comprised of hapi, react-router, alt, webpack, ES6 support, etc. sometime in the not so distant future.

**Comment by apaatsio** [comment]
Sounds good :+1:
